publish_mode: editorial_workflow
site_url: https://nuevos-comienzos.org
locale: 'es'

backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: static/images/uploads
public_folder: /images

collections:
  - name: 'activities'
    label: 'Activities'
    folder: 'content/activities'
    create: true
    slug: '{{year}}-{{month}}-{{day}}_{{slug}}'
    media_folder: ''
    public_folder: ''
    path: '{{title}}/index'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Activity Date', name: 'date', widget: 'datetime' }
      - { label: 'Repeats', name: 'repeats', widget: 'boolean' }
      - { label: 'Description', name: 'description', widget: 'string' }